name: Discord Bot 24/7 (Scuffed)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          SNUSBASE_API_KEY: ${{ secrets.SNUSBASE_API_KEY }}
        run: |
          python bot.py
      - name: Self-trigger workflow for "infinite" uptime
        if: always()
        run: |
          gh workflow run bot.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
